const Sprite = require('./sprite');


let easy_deck = {
    okc: { 1: { value: 1, color: 'black', type: 'chicken' } },
    okp: { 1: { value: 1, color: 'black', type: 'pig' } },
    oks: { 1: { value: 1, color: 'black', type: 'sheep' } },
    obc: { 1: { value: 1, color: 'blue', type: 'chicken' } },
    obp: { 1: { value: 1, color: 'blue', type: 'pig' } },
    obs: { 1: { value: 1, color: 'blue', type: 'sheep' } },
    obw: { 1: { value: 1, color: 'blue', type: 'wild' } },
    orc: { 1: { value: 1, color: 'red', type: 'chicken' } },
    orp: { 1: { value: 1, color: 'red', type: 'pig' } },
    ors: { 1: { value: 1, color: 'red', type: 'sheep' } },
    orw: { 1: { value: 1, color: 'red', type: 'wild' } },
    oyc: { 1: { value: 1, color: 'yellow', type: 'chicken' } },
    oyp: { 1: { value: 1, color: 'yellow', type: 'pig' } },
    oys: { 1: { value: 1, color: 'yellow', type: 'sheep' } },
    oyw: { 1: { value: 1, color: 'yellow', type: 'wild' } },

    tkc: { 1: { value: 2, color: 'black', type: 'chicken' } },
    tkp: { 1: { value: 2, color: 'black', type: 'pig' } },
    tks: { 1: { value: 2, color: 'black', type: 'sheep' } },
    tbc: { 1: { value: 2, color: 'blue', type: 'chicken' } },
    tbp: { 1: { value: 2, color: 'blue', type: 'pig' } },
    tbs: { 1: { value: 2, color: 'blue', type: 'sheep' } },
    tbw: { 1: { value: 2, color: 'blue', type: 'wild' } },
    trc: { 1: { value: 2, color: 'red', type: 'chicken' } },
    trp: { 1: { value: 2, color: 'red', type: 'pig' } },
    trs: { 1: { value: 2, color: 'red', type: 'sheep' } },
    trw: { 1: { value: 2, color: 'red', type: 'wild' } },
    tyc: { 1: { value: 2, color: 'yellow', type: 'chicken' } },
    typ: { 1: { value: 2, color: 'yellow', type: 'pig' } },
    tys: { 1: { value: 2, color: 'yellow', type: 'yellow' } },
    tyw: { 1: { value: 2, color: 'yellow', type: 'wild' } },

    obcorp: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'pig' } },
    obcoyp: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'pig' } },
    obpors: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    obcoys: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    obcorc: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    obporp: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'red', type: 'pig' } },
    obsors: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    obsorc: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    obsoyc: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    obpobc: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    orporc: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    oypoyc: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    obpobs: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    orpors: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    oypoys: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    orcobp: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'pig' } },
    orcoyp: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'pig' } },
    orpobs: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    orpoys: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    orsobc: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    orsoyc: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    orcoyc: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    orpoyp: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'pig' } },
    orsoys: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    obsobc: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    orsorc: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    oysoyc: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    oycobc: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    oypobp: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'pig' } },
    oysobs: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    oycobp: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'pig' } },
    oycorp: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'pig' } },
    oypobs: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    oypors: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    oysobc: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    oysorc: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'chicken' } },

    nokc: { 1: { value: -1, color: 'black', type: 'chicken' } },
    nokp: { 1: { value: -1, color: 'black', type: 'pig' } },
    noks: { 1: { value: -1, color: 'black', type: 'sheep' } },
    nobc: { 1: { value: -1, color: 'blue', type: 'chicken' } },
    nobp: { 1: { value: -1, color: 'blue', type: 'pig' } },
    nobs: { 1: { value: -1, color: 'blue', type: 'sheep' } },
    norc: { 1: { value: -1, color: 'red', type: 'chicken' } },
    norp: { 1: { value: -1, color: 'red', type: 'pig' } },
    nors: { 1: { value: -1, color: 'red', type: 'sheep' } },
    noyc: { 1: { value: -1, color: 'yellow', type: 'chicken' } },
    noyp: { 1: { value: -1, color: 'yellow', type: 'pig' } },
    noys: { 1: { value: -1, color: 'yellow', type: 'sheep' } },

    ntkc: { 1: { value: -2, color: 'black', type: 'chicken' } },
    ntkp: { 1: { value: -2, color: 'black', type: 'pig' } },
    ntks: { 1: { value: -2, color: 'black', type: 'sheep' } },
    ntbc: { 1: { value: -2, color: 'blue', type: 'chicken' } },
    ntbp: { 1: { value: -2, color: 'blue', type: 'pig' } },
    ntbs: { 1: { value: -2, color: 'blue', type: 'sheep' } },
    ntrc: { 1: { value: -2, color: 'red', type: 'chicken' } },
    ntrp: { 1: { value: -2, color: 'red', type: 'pig' } },
    ntrs: { 1: { value: -2, color: 'red', type: 'sheep' } },
    ntyc: { 1: { value: -2, color: 'yellow', type: 'chicken' } },
    ntyp: { 1: { value: -2, color: 'yellow', type: 'pig' } },
    ntys: { 1: { value: -2, color: 'yellow', type: 'sheep' } },

    hyw: { 1: { value: 3, color: 'yellow', type: 'wild' } },
    hrw: { 1: { value: 3, color: 'red', type: 'wild' } },
    hbw: { 1: { value: 3, color: 'blue', type: 'wild' } },

    hkc: { 1: { value: 3, color: 'black', type: 'chicken' } },
    hks: { 1: { value: 3, color: 'black', type: 'sheep' } },
    hkp: { 1: { value: 3, color: 'black', type: 'pig' } },

    oycoysoyp: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'sheep' }, 3: { value: 1, color: 'yellow', type: 'pig' } },
    orcorsorp: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'sheep' }, 3: { value: 1, color: 'red', type: 'pig' } },
    obcobsobp: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'sheep' }, 3: { value: 1, color: 'blue', type: 'pig' } },
    okcobsokp: { 1: { value: 1, color: 'black', type: 'chicken' }, 2: { value: 1, color: 'black', type: 'sheep' }, 3: { value: 1, color: 'black', type: 'pig' } },
    oycorcobc: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'chicken' }, 3: { value: 1, color: 'blue', type: 'chicken' } },
    oysorsobs: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'sheep' }, 3: { value: 1, color: 'blue', type: 'sheep' } },
    oyporpobp: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'red', type: 'pig' }, 3: { value: 1, color: 'blue', type: 'pig' } },

}
// o is one
// t is two
// h is three

// b is black
// u is blue
// r is red
// y is yellow

// c is chicken
// p is pig
// s is sheep
// w is wild

// n is negative
let sum_deck = {
    ucrp: {values: [{ color: 'blue', type: 'chicken'},{color: 'red', type: 'pig'}]},
    ucyp: {values: [{ color: 'blue', type: 'chicken'},{color: 'yellow', type: 'pig'}]},
    uprs: {values: [{ color: 'blue', type: 'pig'},{color: 'red', type: 'sheep'}]},
    upys: {values: [{ color: 'blue', type: 'pig'},{color: 'yellow', type: 'sheep'}]},
    usrc: {values: [{ color: 'blue', type: 'sheep'},{color: 'red', type: 'chicken'}]},
    usyc: {values: [{ color: 'blue', type: 'sheep'},{color: 'yellow', type: 'chicken'}]},
    rcbp: {values: [{ color: 'red', type: 'chicken'},{color: 'blue', type: 'pig'}]},
    rcyp: {values: [{ color: 'red', type: 'chicken'},{color: 'yellow', type: 'pig'}]},
    rpbs: {values: [{ color: 'red', type: 'pig'},{color: 'blue', type: 'sheep'}]},
    rpys: {values: [{ color: 'red', type: 'pig'},{color: 'yellow', type: 'sheep'}]},
    rsbc: {values: [{ color: 'red', type: 'sheep'},{color: 'blue', type: 'chicken'}]},
    rsyc: {values: [{ color: 'red', type: 'sheep'},{color: 'yellow', type: 'chicken'}]},
    ycbp: {values: [{ color: 'yellow', type: 'chicken'},{color: 'blue', type: 'pig'}]},
    ycrp: {values: [{ color: 'yellow', type: 'chicken'},{color: 'red', type: 'pig'}]},
    ypbs: {values: [{ color: 'yellow', type: 'pig'},{color: 'blue', type: 'sheep'}]},
    yprs: {values: [{ color: 'yellow', type: 'pig'},{color: 'red', type: 'sheep'}]},
    ysbc: {values: [{ color: 'yellow', type: 'sheep'},{color: 'blue', type: 'chicken'}]},
    ysrc: {values: [{ color: 'yellow', type: 'sheep'},{color: 'red', type: 'chicken'}]},
    uw: {values: [{ color: 'blue', type: 'wild' }]},
    rw: {values: [{ color: 'red', type: 'wild' }] },
    yw: {values: [{ color: 'yellow', type: 'wild' }] },
    bc: {values: [{ color: 'black', type: 'chicken' }]},
    bp: {values: [{ color: 'black', type: 'pig' }]},
    bs: {values: [{ color: 'black', type: 'sheep' }]}
}

let sprites = {
    okc: new Sprite('/Images/1blackchicken.png', 675, 1050),
    okp: new Sprite('/Images/1blackpig.png', 675, 1050),
    oks: new Sprite('/Images/1blacksheep.png', 675, 1050),
    obc: new Sprite('/Images/1bluechicken.png', 675, 1050),
    obp: new Sprite('/Images/1bluepig.png', 675, 1050),
    obs: new Sprite('/Images/1bluesheep.png', 675, 1050),
    obw: new Sprite('/Images/1bluestar.png', 675, 1050),
    orc: new Sprite('/Images/1redchicken.png', 675, 1050),
    orp: new Sprite('/Images/1redpig.png', 675, 1050),
    ors: new Sprite('/Images/1redsheep.png', 675, 1050),
    orw: new Sprite('/Images/1redstar.png', 675, 1050),
    oyc: new Sprite('/Images/1yellowchicken.png', 675, 1050),
    oyp: new Sprite('/Images/1yellowpig.png', 675, 1050),
    oys: new Sprite('/Images/1yellowsheep.png', 675, 1050),
    oyw: new Sprite('/Images/1yellowstar.png', 675, 1050),

    tkc: new Sprite('/Images/2blackchicken.png', 675, 1050),
    tkp: new Sprite('/Images/2blackpig.png', 675, 1050),
    tks: new Sprite('/Images/2blacksheep.png', 675, 1050),
    tbc: new Sprite('/Images/2bluechicken.png', 675, 1050),
    tbp: new Sprite('/Images/2bluepig.png', 675, 1050),
    tbs: new Sprite('/Images/2bluesheep.png', 675, 1050),
    tbw: new Sprite('/Images/2bluestar.png', 675, 1050),
    trc: new Sprite('/Images/2redchicken.png', 675, 1050),
    trp: new Sprite('/Images/2redpig.png', 675, 1050),
    trs: new Sprite('/Images/2redsheep.png', 675, 1050),
    trw: new Sprite('/Images/2redstar.png', 675, 1050),
    tyc: new Sprite('/Images/2yellowchicken.png', 675, 1050),
    typ: new Sprite('/Images/2yellowpig.png', 675, 1050),
    tys: new Sprite('/Images/2yellowsheep.png', 675, 1050),
    tyw: new Sprite('/Images/2yellowstar.png', 675, 1050),

    obcorp: new Sprite('/Images/2bluechickenredpig.png', 675, 1050),
    obcoyp: new Sprite('/Images/2bluechickenyellowpig.png', 675, 1050),
    obpors: new Sprite('/Images/2bluepigredsheep.png', 675, 1050),
    obcoys: new Sprite('/Images/2bluepigyellowsheep.png', 675, 1050),
    obcorc: new Sprite('/Images/2blueredchicken.png', 675, 1050),
    obporp: new Sprite('/Images/2blueredpig.png', 675, 1050),
    obsors: new Sprite('/Images/2blueredsheep.png', 675, 1050),
    obsorc: new Sprite('/Images/2bluesheepredchicken.png', 675, 1050),
    obsoyc: new Sprite('/Images/2bluesheepyellowchicken.png', 675, 1050),
    obpobc: new Sprite('/Images/2pigchickenblue.png', 675, 1050),
    orporc: new Sprite('/Images/2pigchickenred.png', 675, 1050),
    oypoyc: new Sprite('/Images/2pigchickenyellow.png', 675, 1050),
    obpobs: new Sprite('/Images/2pigsheepblue.png', 675, 1050),
    orpors: new Sprite('/Images/2pigsheepred.png', 675, 1050),
    oypoys: new Sprite('/Images/2pigsheepyellow.png', 675, 1050),
    orcobp: new Sprite('/Images/2redchickenbluepig.png', 675, 1050),
    orcoyp: new Sprite('/Images/2redchickenyellowpig.png', 675, 1050),
    orpobs: new Sprite('/Images/2redpigbluesheep.png', 675, 1050),
    orpoys: new Sprite('/Images/2redpigyellowsheep.png', 675, 1050),
    orsobc: new Sprite('/Images/2redsheepbluechicken.png', 675, 1050),
    orsoyc: new Sprite('/Images/2redsheepyellowchicken.png', 675, 1050),
    orcoyc: new Sprite('/Images/2redyellowchicken.png', 675, 1050),
    orpoyp: new Sprite('/Images/2redyellowpig.png', 675, 1050),
    orsoys: new Sprite('/Images/2redyellowsheep.png', 675, 1050),
    obsobc: new Sprite('/Images/2sheepchickenblue.png', 675, 1050),
    orsorc: new Sprite('/Images/2sheepchickenred.png', 675, 1050),
    oysoyc: new Sprite('/Images/2sheepchickenyellow.png', 675, 1050),
    oycobc: new Sprite('/Images/2yellowbluechicken.png', 675, 1050),
    oypobp: new Sprite('/Images/2yellowbluepig.png', 675, 1050),
    oysobs: new Sprite('/Images/2yellowbluesheep.png', 675, 1050),
    oycobp: new Sprite('/Images/2yellowchickenbluepig.png', 675, 1050),
    oycorp: new Sprite('/Images/2yellowchickenredpig.png', 675, 1050),
    oypobs: new Sprite('/Images/2yellowpigbluesheep.png', 675, 1050),
    oypors: new Sprite('/Images/2yellowpigredsheep.png', 675, 1050),
    oysobc: new Sprite('/Images/2yellowsheepbluechicken.png', 675, 1050),
    oysorc: new Sprite('/Images/2yellowsheepredchicken.png', 675, 1050),

    nokc: new Sprite('/Images/N1blackchicken.png', 675, 1050),
    nokp: new Sprite('/Images/N1blackpig.png', 675, 1050),
    noks: new Sprite('/Images/N1blacksheep.png', 675, 1050),
    nobc: new Sprite('/Images/N1bluechicken.png', 675, 1050),
    nobp: new Sprite('/Images/N1bluepig.png', 675, 1050),
    nobs: new Sprite('/Images/N1bluesheep.png', 675, 1050),
    norc: new Sprite('/Images/N1redchicken.png', 675, 1050),
    norp: new Sprite('/Images/N1redpig.png', 675, 1050),
    nors: new Sprite('/Images/N1redsheep.png', 675, 1050),
    noyc: new Sprite('/Images/N1yellowchicken.png', 675, 1050),
    noyp: new Sprite('/Images/N1yellowpig.png', 675, 1050),
    noys: new Sprite('/Images/N1yellowsheep.png', 675, 1050),

    ntkc: new Sprite('/Images/N2blackchicken.png', 675, 1050),
    ntkp: new Sprite('/Images/N2blackpig.png', 675, 1050),
    ntks: new Sprite('/Images/N2blacksheep.png', 675, 1050),
    ntbc: new Sprite('/Images/N2bluechicken.png', 675, 1050),
    ntbp: new Sprite('/Images/N2bluepig.png', 675, 1050),
    ntbs: new Sprite('/Images/N2bluesheep.png', 675, 1050),
    ntrc: new Sprite('/Images/N2redchicken.png', 675, 1050),
    ntrp: new Sprite('/Images/N2redpig.png', 675, 1050),
    ntrs: new Sprite('/Images/N2redsheep.png', 675, 1050),
    ntyc: new Sprite('/Images/N2yellowchicken.png', 675, 1050),
    ntyp: new Sprite('/Images/N2yellowpig.png', 675, 1050),
    ntys: new Sprite('/Images/N2yellowsheep.png', 675, 1050),

    hyw: new Sprite('/Images/3yellowstar.png', 675, 1050),
    hrw: new Sprite('/Images/3redstar.png', 675, 1050),
    hbw: new Sprite('/Images/3bluestar.png', 675, 1050),

    hkc: new Sprite('/Images/3blackchicken.png', 675, 1050),
    hks: new Sprite('/Images/3blacksheep.png', 675, 1050),
    hkp: new Sprite('/Images/3blackpig.png', 675, 1050),

    oycoysoyp: new Sprite('/Images/3wildyellow.png', 675, 1050),
    orcorsorp: new Sprite('/Images/3wildred.png', 675, 1050),
    obcobsobp: new Sprite('/Images/3wildblue.png', 675, 1050),
    okcobsokp: new Sprite('/Images/3wildblack.png', 675, 1050),
    oycorcobc: new Sprite('/Images/3wildchicken.png', 675, 1050),
    oysorsobs: new Sprite('/Images/3wildsheep.png', 675, 1050),
    oyporpobp: new Sprite('/Images/3wildpig.png', 675, 1050),

    ucrp: new Sprite('/Images/Sumbluechickenredpig.png', 675, 1050),
    ucyp: new Sprite('/Images/Sumbluechickenyellowpig.png', 675, 1050),
    uprs: new Sprite('/Images/Sumbluepigredsheep.png', 675, 1050),
    upys: new Sprite('/Images/Sumbluepigyellowsheep.png', 675, 1050),
    usrc: new Sprite('/Images/Sumbluesheepredchicken.png', 675, 1050),
    usyc: new Sprite('/Images/Sumbluesheepyellowchicken.png', 675, 1050),
    rcbp: new Sprite('/Images/Sumredchickenbluepig.png', 675, 1050),
    rcyp: new Sprite('/Images/Sumredchickenyellowpig.png', 675, 1050),
    rpbs: new Sprite('/Images/Sumredpigbluesheep.png', 675, 1050),
    rpys: new Sprite('/Images/Sumredpigyellowsheep.png', 675, 1050),
    rsbc: new Sprite('/Images/Sumredsheepbluechicken.png', 675, 1050),
    rsyc: new Sprite('/Images/Sumredsheepyellowchicken.png', 675, 1050),
    ycbp: new Sprite('/Images/Sumyellowchickenbluepig.png', 675, 1050),
    ycrp: new Sprite('/Images/Sumyellowchickenredpig.png', 675, 1050),
    ypbs: new Sprite('/Images/Sumyellowpigbluesheep.png', 675, 1050),
    yprs: new Sprite('/Images/Sumyellowpigredsheep.png', 675, 1050),
    ysbc: new Sprite('/Images/Sumyellowsheepbluechicken.png', 675, 1050),
    ysrc: new Sprite('/Images/Sumyellowsheepredchicken.png', 675, 1050),
    uw: new Sprite('/Images/TotalBlue.png', 675, 1050),
    rw: new Sprite('/Images/TotalRed.png', 675, 1050),
    yw: new Sprite('/Images/TotalYellow.png', 675, 1050),
    bc: new Sprite('/Images/Totalchicken.png', 675, 1050),
    bp: new Sprite('/Images/Totalpig.png', 675, 1050),
    bs: new Sprite('/Images/Totalsheep.png', 675, 1050),

    dbr: new Sprite('/Images/DifferenceBlueRed.png', 675, 1050),
    dcp: new Sprite('/Images/Differencechickenpig.png', 675, 1050),
    dps: new Sprite('/Images/Differencepigsheep.png', 675, 1050),
    dry: new Sprite('/Images/DifferenceRedYellow.png', 675, 1050),
    dsc: new Sprite('/Images/Differencesheepchicken.png', 675, 1050),
    dyb: new Sprite('/Images/DifferenceYellowBlue.png', 675, 1050),

    dh: new Sprite('/Images/DoubleHorizontal.png', 675, 1050),
    dv: new Sprite('/Images/DoubleVertical.png', 675, 1050),
    oh: new Sprite('/Images/OppositeHorizontal.png', 675, 1050),
    ov: new Sprite('/Images/OppositeVertical.png', 675, 1050),
    hvb: new Sprite('/Images/Tripleverticalblue.png', 675, 1050),
    hvr: new Sprite('/Images/Tripleverticalred.png', 675, 1050),
    hvy: new Sprite('/Images/Tripleverticalyellow.png', 675, 1050),
    hdo: new Sprite('/Images/x3Diagonal1.png', 675, 1050),
    hdt: new Sprite('/Images/x3Diagonal2.png', 675, 1050),

    dbr2: new Sprite('/Images/DifferenceBlueRed.png', 675, 1050),
    dcp2: new Sprite('/Images/Differencechickenpig.png', 675, 1050),
    dps2: new Sprite('/Images/Differencepigsheep.png', 675, 1050),
    dry2: new Sprite('/Images/DifferenceRedYellow.png', 675, 1050),
    dsc2: new Sprite('/Images/Differencesheepchicken.png', 675, 1050),
    dyb2: new Sprite('/Images/DifferenceYellowBlue.png', 675, 1050),

    dh2: new Sprite('/Images/DoubleHorizontal.png', 675, 1050),
    dv2: new Sprite('/Images/DoubleVertical.png', 675, 1050),
    oh2: new Sprite('/Images/OppositeHorizontal.png', 675, 1050),
    ov2: new Sprite('/Images/OppositeVertical.png', 675, 1050),
    hvb2: new Sprite('/Images/Tripleverticalblue.png', 675, 1050),
    hvr2: new Sprite('/Images/Tripleverticalred.png', 675, 1050),
    hvy2: new Sprite('/Images/Tripleverticalyellow.png', 675, 1050),
    hdo2: new Sprite('/Images/x3Diagonal1.png', 675, 1050),
    hdt2: new Sprite('/Images/x3Diagonal2.png', 675, 1050),
}

// let hard_deck = easy_deck;
// let diff_deck = sum_deck;

let diff_cards = {
    dbr: {values: [{ color: 'blue', type: 'wild'},{color: 'red', type: 'wild'}]},
    dcp: {values: [{ color: 'black', type: 'chicken'},{color: 'black', type: 'pig'}]},
    dps: {values: [{ color: 'black', type: 'pig'},{color: 'black', type: 'sheep'}]},
    dry: {values: [{ color: 'red', type: 'wild'},{color: 'yellow', type: 'wild'}]},
    dsc: {values: [{ color: 'black', type: 'sheep'},{color: 'black', type: 'chicken'}]},
    dyb: {values: [{ color: 'yellow', type: 'wild'},{color: 'blue', type: 'wild'}]}
}

let hard_cards = {
    dh: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: 2 } },
    dv: { 1: { value: 0, direction: 'vertical', color: 'black', amount: 2} },
    oh: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: -1} },
    ov: { 1: { value: 0, direction: 'vertical', color: 'black', amount: -1} },
    hvb: { 1: { value: 0, direction: 'vertical', color: 'blue', amount: 3} },
    hvr: { 1: { value: 0, direction: 'vertical', color: 'red', amount: 3} },
    hvy: { 1: { value: 0, direction: 'vertical', color: 'yellow', amount: 3} },
    hdo: { 1: { value: 0, direction: 'diagonal1', color: 'black', amount: 3} },
    hdt: { 1: { value: 0, direction: 'diagonal2', color: 'black', amount: 3} }
}
let hard_cards2 = {
    dh2: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: 2 } },
    dv2: { 1: { value: 0, direction: 'vertical', color: 'black', amount: 2 } },
    oh2: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: -1 } },
    ov2: { 1: { value: 0, direction: 'vertical', color: 'black', amount: -1 } },
    hvb2: { 1: { value: 0, direction: 'vertical', color: 'blue', amount: 3 } },
    hvr2: { 1: { value: 0, direction: 'vertical', color: 'red', amount: 3 } },
    hvy2: { 1: { value: 0, direction: 'vertical', color: 'yellow', amount: 3 } },
    hdo2: { 1: { value: 0, direction: 'diagonal1', color: 'black', amount: 3 } },
    hdt2: { 1: { value: 0, direction: 'diagonal2', color: 'black', amount: 3 } }
}
let hard_deck = {...easy_deck, ...hard_cards};
let diff_deck = {...sum_deck, ...diff_cards};

let harder_deck = {...easy_deck, ...hard_cards, ...hard_cards2};

module.exports = { sum_deck, diff_deck, easy_deck, hard_deck, harder_deck, sprites}