const Sprite = require('./sprite');


let easy_deck = {
    okc: { 1: { value: 1, color: 'black', type: 'chicken' } },
    okp: { 1: { value: 1, color: 'black', type: 'pig' } },
    oks: { 1: { value: 1, color: 'black', type: 'sheep' } },
    obc: { 1: { value: 1, color: 'blue', type: 'chicken' } },
    obp: { 1: { value: 1, color: 'blue', type: 'pig' } },
    obs: { 1: { value: 1, color: 'blue', type: 'sheep' } },
    obw: { 1: { value: 1, color: 'blue', type: 'wild' } },
    orc: { 1: { value: 1, color: 'red', type: 'chicken' } },
    orp: { 1: { value: 1, color: 'red', type: 'pig' } },
    ors: { 1: { value: 1, color: 'red', type: 'sheep' } },
    orw: { 1: { value: 1, color: 'red', type: 'wild' } },
    oyc: { 1: { value: 1, color: 'yellow', type: 'chicken' } },
    oyp: { 1: { value: 1, color: 'yellow', type: 'pig' } },
    oys: { 1: { value: 1, color: 'yellow', type: 'sheep' } },
    oyw: { 1: { value: 1, color: 'yellow', type: 'wild' } },

    tkc: { 1: { value: 2, color: 'black', type: 'chicken' } },
    tkp: { 1: { value: 2, color: 'black', type: 'pig' } },
    tks: { 1: { value: 2, color: 'black', type: 'sheep' } },
    tbc: { 1: { value: 2, color: 'blue', type: 'chicken' } },
    tbp: { 1: { value: 2, color: 'blue', type: 'pig' } },
    tbs: { 1: { value: 2, color: 'blue', type: 'sheep' } },
    tbw: { 1: { value: 2, color: 'blue', type: 'wild' } },
    trc: { 1: { value: 2, color: 'red', type: 'chicken' } },
    trp: { 1: { value: 2, color: 'red', type: 'pig' } },
    trs: { 1: { value: 2, color: 'red', type: 'sheep' } },
    trw: { 1: { value: 2, color: 'red', type: 'wild' } },
    tyc: { 1: { value: 2, color: 'yellow', type: 'chicken' } },
    typ: { 1: { value: 2, color: 'yellow', type: 'pig' } },
    tys: { 1: { value: 2, color: 'yellow', type: 'yellow' } },
    tyw: { 1: { value: 2, color: 'yellow', type: 'wild' } },

    obcorp: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'pig' } },
    obcoyp: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'pig' } },
    obpors: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    obcoys: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    obcorc: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    obporp: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'red', type: 'pig' } },
    obsors: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    obsorc: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    obsoyc: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    obpobc: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    orporc: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    oypoyc: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    obpobs: { 1: { value: 1, color: 'blue', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    orpors: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    oypoys: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    orcobp: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'pig' } },
    orcoyp: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'pig' } },
    orpobs: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    orpoys: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    orsobc: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    orsoyc: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    orcoyc: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    orpoyp: { 1: { value: 1, color: 'red', type: 'pig' }, 2: { value: 1, color: 'yellow', type: 'pig' } },
    orsoys: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'sheep' } },
    obsobc: { 1: { value: 1, color: 'blue', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    orsorc: { 1: { value: 1, color: 'red', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'chicken' } },
    oysoyc: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'yellow', type: 'chicken' } },
    oycobc: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    oypobp: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'pig' } },
    oysobs: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    oycobp: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'pig' } },
    oycorp: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'pig' } },
    oypobs: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'blue', type: 'sheep' } },
    oypors: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'red', type: 'sheep' } },
    oysobc: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'blue', type: 'chicken' } },
    oysorc: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'chicken' } },

    nokc: { 1: { value: -1, color: 'black', type: 'chicken' } },
    nokp: { 1: { value: -1, color: 'black', type: 'pig' } },
    noks: { 1: { value: -1, color: 'black', type: 'sheep' } },
    nobc: { 1: { value: -1, color: 'blue', type: 'chicken' } },
    nobp: { 1: { value: -1, color: 'blue', type: 'pig' } },
    nobs: { 1: { value: -1, color: 'blue', type: 'sheep' } },
    norc: { 1: { value: -1, color: 'red', type: 'chicken' } },
    norp: { 1: { value: -1, color: 'red', type: 'pig' } },
    nors: { 1: { value: -1, color: 'red', type: 'sheep' } },
    noyc: { 1: { value: -1, color: 'yellow', type: 'chicken' } },
    noyp: { 1: { value: -1, color: 'yellow', type: 'pig' } },
    noys: { 1: { value: -1, color: 'yellow', type: 'sheep' } },

    ntkc: { 1: { value: -2, color: 'black', type: 'chicken' } },
    ntkp: { 1: { value: -2, color: 'black', type: 'pig' } },
    ntks: { 1: { value: -2, color: 'black', type: 'sheep' } },
    ntbc: { 1: { value: -2, color: 'blue', type: 'chicken' } },
    ntbp: { 1: { value: -2, color: 'blue', type: 'pig' } },
    ntbs: { 1: { value: -2, color: 'blue', type: 'sheep' } },
    ntrc: { 1: { value: -2, color: 'red', type: 'chicken' } },
    ntrp: { 1: { value: -2, color: 'red', type: 'pig' } },
    ntrs: { 1: { value: -2, color: 'red', type: 'sheep' } },
    ntyc: { 1: { value: -2, color: 'yellow', type: 'chicken' } },
    ntyp: { 1: { value: -2, color: 'yellow', type: 'pig' } },
    ntys: { 1: { value: -2, color: 'yellow', type: 'sheep' } },

    hyw: { 1: { value: 3, color: 'yellow', type: 'wild' } },
    hrw: { 1: { value: 3, color: 'red', type: 'wild' } },
    hbw: { 1: { value: 3, color: 'blue', type: 'wild' } },

    hkc: { 1: { value: 3, color: 'black', type: 'chicken' } },
    hks: { 1: { value: 3, color: 'black', type: 'sheep' } },
    hkp: { 1: { value: 3, color: 'black', type: 'pig' } },

    oycoysoyp: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'yellow', type: 'sheep' }, 3: { value: 1, color: 'yellow', type: 'pig' } },
    orcorsorp: { 1: { value: 1, color: 'red', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'sheep' }, 3: { value: 1, color: 'red', type: 'pig' } },
    obcobsobp: { 1: { value: 1, color: 'blue', type: 'chicken' }, 2: { value: 1, color: 'blue', type: 'sheep' }, 3: { value: 1, color: 'blue', type: 'pig' } },
    okcobsokp: { 1: { value: 1, color: 'black', type: 'chicken' }, 2: { value: 1, color: 'black', type: 'sheep' }, 3: { value: 1, color: 'black', type: 'pig' } },
    oycorcobc: { 1: { value: 1, color: 'yellow', type: 'chicken' }, 2: { value: 1, color: 'red', type: 'chicken' }, 3: { value: 1, color: 'blue', type: 'chicken' } },
    oysorsobs: { 1: { value: 1, color: 'yellow', type: 'sheep' }, 2: { value: 1, color: 'red', type: 'sheep' }, 3: { value: 1, color: 'blue', type: 'sheep' } },
    oyporpobp: { 1: { value: 1, color: 'yellow', type: 'pig' }, 2: { value: 1, color: 'red', type: 'pig' }, 3: { value: 1, color: 'blue', type: 'pig' } },

}
// o is one
// t is two
// h is three

// k is black
// b is blue
// r is red
// y is yellow

// c is chicken
// p is pig
// s is sheep
// w is wild

// n is negative
let sum_deck = {
    ucrp: {values: [{ color: 'blue', type: 'chicken'},{color: 'red', type: 'pig'}]},
    ucyp: {values: [{ color: 'blue', type: 'chicken'},{color: 'yellow', type: 'pig'}]},
    uprs: {values: [{ color: 'blue', type: 'pig'},{color: 'red', type: 'sheep'}]},
    upys: {values: [{ color: 'blue', type: 'pig'},{color: 'yellow', type: 'sheep'}]},
    usrc: {values: [{ color: 'blue', type: 'sheep'},{color: 'red', type: 'chicken'}]},
    usyc: {values: [{ color: 'blue', type: 'sheep'},{color: 'yellow', type: 'chicken'}]},
    rcbp: {values: [{ color: 'red', type: 'chicken'},{color: 'blue', type: 'pig'}]},
    rcyp: {values: [{ color: 'red', type: 'chicken'},{color: 'yellow', type: 'pig'}]},
    rpbs: {values: [{ color: 'red', type: 'pig'},{color: 'blue', type: 'sheep'}]},
    rpys: {values: [{ color: 'red', type: 'pig'},{color: 'yellow', type: 'sheep'}]},
    rsbc: {values: [{ color: 'red', type: 'sheep'},{color: 'blue', type: 'chicken'}]},
    rsyc: {values: [{ color: 'red', type: 'sheep'},{color: 'yellow', type: 'chicken'}]},
    ycbp: {values: [{ color: 'yellow', type: 'chicken'},{color: 'blue', type: 'pig'}]},
    ycrp: {values: [{ color: 'yellow', type: 'chicken'},{color: 'red', type: 'pig'}]},
    ypbs: {values: [{ color: 'yellow', type: 'pig'},{color: 'blue', type: 'sheep'}]},
    yprs: {values: [{ color: 'yellow', type: 'pig'},{color: 'red', type: 'sheep'}]},
    ysbc: {values: [{ color: 'yellow', type: 'sheep'},{color: 'blue', type: 'chicken'}]},
    ysrc: {values: [{ color: 'yellow', type: 'sheep'},{color: 'red', type: 'chicken'}]},
    uw: {values: [{ color: 'blue', type: 'wild' }]},
    rw: {values: [{ color: 'red', type: 'wild' }] },
    yw: {values: [{ color: 'yellow', type: 'wild' }] },
    bc: {values: [{ color: 'black', type: 'chicken' }]},
    bp: {values: [{ color: 'black', type: 'pig' }]},
    bs: {values: [{ color: 'black', type: 'sheep' }]}
}

let sprites = {
    okc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1blackchicken.png', 675, 1050),
    okp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1blackpig.png', 675, 1050),
    oks: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1blacksheep.png', 675, 1050),
    obc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1bluechicken.png', 675, 1050),
    obp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1bluepig.png', 675, 1050),
    obs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1bluesheep.png', 675, 1050),
    obw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1bluestar.png', 675, 1050),
    orc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1redchicken.png', 675, 1050),
    orp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1redpig.png', 675, 1050),
    ors: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1redsheep.png', 675, 1050),
    orw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1redstar.png', 675, 1050),
    oyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1yellowchicken.png', 675, 1050),
    oyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1yellowpig.png', 675, 1050),
    oys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1yellowsheep.png', 675, 1050),
    oyw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/1yellowstar.png', 675, 1050),

    tkc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2blackchicken.png', 675, 1050),
    tkp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2blackpig.png', 675, 1050),
    tks: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2blacksheep.png', 675, 1050),
    tbc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluechicken.png', 675, 1050),
    tbp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluepig.png', 675, 1050),
    tbs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluesheep.png', 675, 1050),
    tbw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluestar.png', 675, 1050),
    trc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redchicken.png', 675, 1050),
    trp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redpig.png', 675, 1050),
    trs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redsheep.png', 675, 1050),
    trw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redstar.png', 675, 1050),
    tyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowchicken.png', 675, 1050),
    typ: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowpig.png', 675, 1050),
    tys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowsheep.png', 675, 1050),
    tyw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowstar.png', 675, 1050),

    obcorp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluechickenredpig.png', 675, 1050),
    obcoyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluechickenyellowpig.png', 675, 1050),
    obpors: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluepigredsheep.png', 675, 1050),
    obcoys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluepigyellowsheep.png', 675, 1050),
    obcorc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2blueredchicken.png', 675, 1050),
    obporp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2blueredpig.png', 675, 1050),
    obsors: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2blueredsheep.png', 675, 1050),
    obsorc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluesheepredchicken.png', 675, 1050),
    obsoyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2bluesheepyellowchicken.png', 675, 1050),
    obpobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2pigchickenblue.png', 675, 1050),
    orporc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2pigchickenred.png', 675, 1050),
    oypoyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2pigchickenyellow.png', 675, 1050),
    obpobs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2pigsheepblue.png', 675, 1050),
    orpors: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2pigsheepred.png', 675, 1050),
    oypoys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2pigsheepyellow.png', 675, 1050),
    orcobp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redchickenbluepig.png', 675, 1050),
    orcoyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redchickenyellowpig.png', 675, 1050),
    orpobs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redpigbluesheep.png', 675, 1050),
    orpoys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redpigyellowsheep.png', 675, 1050),
    orsobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redsheepbluechicken.png', 675, 1050),
    orsoyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redsheepyellowchicken.png', 675, 1050),
    orcoyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redyellowchicken.png', 675, 1050),
    orpoyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redyellowpig.png', 675, 1050),
    orsoys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2redyellowsheep.png', 675, 1050),
    obsobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2sheepchickenblue.png', 675, 1050),
    orsorc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2sheepchickenred.png', 675, 1050),
    oysoyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2sheepchickenyellow.png', 675, 1050),
    oycobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowbluechicken.png', 675, 1050),
    oypobp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowbluepig.png', 675, 1050),
    oysobs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowbluesheep.png', 675, 1050),
    oycobp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowchickenbluepig.png', 675, 1050),
    oycorp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowchickenredpig.png', 675, 1050),
    oypobs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowpigbluesheep.png', 675, 1050),
    oypors: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowpigredsheep.png', 675, 1050),
    oysobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowsheepbluechicken.png', 675, 1050),
    oysorc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/2yellowsheepredchicken.png', 675, 1050),

    nokc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1blackchicken.png', 675, 1050),
    nokp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1blackpig.png', 675, 1050),
    noks: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1blacksheep.png', 675, 1050),
    nobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1bluechicken.png', 675, 1050),
    nobp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1bluepig.png', 675, 1050),
    nobs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1bluesheep.png', 675, 1050),
    norc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1redchicken.png', 675, 1050),
    norp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1redpig.png', 675, 1050),
    nors: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1redsheep.png', 675, 1050),
    noyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1yellowchicken.png', 675, 1050),
    noyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1yellowpig.png', 675, 1050),
    noys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N1yellowsheep.png', 675, 1050),

    ntkc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2blackchicken.png', 675, 1050),
    ntkp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2blackpig.png', 675, 1050),
    ntks: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2blacksheep.png', 675, 1050),
    ntbc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2bluechicken.png', 675, 1050),
    ntbp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2bluepig.png', 675, 1050),
    ntbs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2bluesheep.png', 675, 1050),
    ntrc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2redchicken.png', 675, 1050),
    ntrp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2redpig.png', 675, 1050),
    ntrs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2redsheep.png', 675, 1050),
    ntyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2yellowchicken.png', 675, 1050),
    ntyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2yellowpig.png', 675, 1050),
    ntys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/N2yellowsheep.png', 675, 1050),

    hyw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3yellowstar.png', 675, 1050),
    hrw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3redstar.png', 675, 1050),
    hbw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3bluestar.png', 675, 1050),

    hkc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3blackchicken.png', 675, 1050),
    hks: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3blacksheep.png', 675, 1050),
    hkp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3blackpig.png', 675, 1050),

    oycoysoyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildyellow.png', 675, 1050),
    orcorsorp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildred.png', 675, 1050),
    obcobsobp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildblue.png', 675, 1050),
    okcobsokp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildblack.png', 675, 1050),
    oycorcobc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildchicken.png', 675, 1050),
    oysorsobs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildsheep.png', 675, 1050),
    oyporpobp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/3wildpig.png', 675, 1050),

    ucrp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumbluechickenredpig.png', 675, 1050),
    ucyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumbluechickenyellowpig.png', 675, 1050),
    uprs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumbluepigredsheep.png', 675, 1050),
    upys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumbluepigyellowsheep.png', 675, 1050),
    usrc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumbluesheepredchicken.png', 675, 1050),
    usyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumbluesheepyellowchicken.png', 675, 1050),
    rcbp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumredchickenbluepig.png', 675, 1050),
    rcyp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumredchickenyellowpig.png', 675, 1050),
    rpbs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumredpigbluesheep.png', 675, 1050),
    rpys: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumredpigyellowsheep.png', 675, 1050),
    rsbc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumredsheepbluechicken.png', 675, 1050),
    rsyc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumredsheepyellowchicken.png', 675, 1050),
    ycbp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumyellowchickenbluepig.png', 675, 1050),
    ycrp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumyellowchickenredpig.png', 675, 1050),
    ypbs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumyellowpigbluesheep.png', 675, 1050),
    yprs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumyellowpigredsheep.png', 675, 1050),
    ysbc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumyellowsheepbluechicken.png', 675, 1050),
    ysrc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Sumyellowsheepredchicken.png', 675, 1050),
    uw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/TotalBlue.png', 675, 1050),
    rw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/TotalRed.png', 675, 1050),
    yw: new Sprite('https://mortezar.github.io/Countin-Chickens/images/TotalYellow.png', 675, 1050),
    bc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Totalchicken.png', 675, 1050),
    bp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Totalpig.png', 675, 1050),
    bs: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Totalsheep.png', 675, 1050),

    dbr: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DifferenceBlueRed.png', 675, 1050),
    dcp: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Differencechickenpig.png', 675, 1050),
    dps: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Differencepigsheep.png', 675, 1050),
    dry: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DifferenceRedYellow.png', 675, 1050),
    dsc: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Differencesheepchicken.png', 675, 1050),
    dyb: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DifferenceYellowBlue.png', 675, 1050),

    dh: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DoubleHorizontal.png', 675, 1050),
    dv: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DoubleVertical.png', 675, 1050),
    oh: new Sprite('https://mortezar.github.io/Countin-Chickens/images/OppositeHorizontal.png', 675, 1050),
    ov: new Sprite('https://mortezar.github.io/Countin-Chickens/images/OppositeVertical.png', 675, 1050),
    hvb: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Tripleverticalblue.png', 675, 1050),
    hvr: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Tripleverticalred.png', 675, 1050),
    hvy: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Tripleverticalyellow.png', 675, 1050),
    hdo: new Sprite('https://mortezar.github.io/Countin-Chickens/images/x3Diagonal1.png', 675, 1050),
    hdt: new Sprite('https://mortezar.github.io/Countin-Chickens/images/x3Diagonal2.png', 675, 1050),

    dbr2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DifferenceBlueRed.png', 675, 1050),
    dcp2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Differencechickenpig.png', 675, 1050),
    dps2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Differencepigsheep.png', 675, 1050),
    dry2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DifferenceRedYellow.png', 675, 1050),
    dsc2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Differencesheepchicken.png', 675, 1050),
    dyb2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DifferenceYellowBlue.png', 675, 1050),

    dh2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DoubleHorizontal.png', 675, 1050),
    dv2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/DoubleVertical.png', 675, 1050),
    oh2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/OppositeHorizontal.png', 675, 1050),
    ov2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/OppositeVertical.png', 675, 1050),
    hvb2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Tripleverticalblue.png', 675, 1050),
    hvr2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Tripleverticalred.png', 675, 1050),
    hvy2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/Tripleverticalyellow.png', 675, 1050),
    hdo2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/x3Diagonal1.png', 675, 1050),
    hdt2: new Sprite('https://mortezar.github.io/Countin-Chickens/images/x3Diagonal2.png', 675, 1050),
}

// let hard_deck = easy_deck;
// let diff_deck = sum_deck;

let diff_cards = {
    dbr: {values: [{ color: 'blue', type: 'wild'},{color: 'red', type: 'wild'}]},
    dcp: {values: [{ color: 'black', type: 'chicken'},{color: 'black', type: 'pig'}]},
    dps: {values: [{ color: 'black', type: 'pig'},{color: 'black', type: 'sheep'}]},
    dry: {values: [{ color: 'red', type: 'wild'},{color: 'yellow', type: 'wild'}]},
    dsc: {values: [{ color: 'black', type: 'sheep'},{color: 'black', type: 'chicken'}]},
    dyb: {values: [{ color: 'yellow', type: 'wild'},{color: 'blue', type: 'wild'}]}
}

let hard_cards = {
    dh: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: 2 } },
    dv: { 1: { value: 0, direction: 'vertical', color: 'black', amount: 2} },
    oh: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: -1} },
    ov: { 1: { value: 0, direction: 'vertical', color: 'black', amount: -1} },
    hvb: { 1: { value: 0, direction: 'vertical', color: 'blue', amount: 3} },
    hvr: { 1: { value: 0, direction: 'vertical', color: 'red', amount: 3} },
    hvy: { 1: { value: 0, direction: 'vertical', color: 'yellow', amount: 3} },
    hdo: { 1: { value: 0, direction: 'diagonal1', color: 'black', amount: 3} },
    hdt: { 1: { value: 0, direction: 'diagonal2', color: 'black', amount: 3} }
}
let hard_cards2 = {
    dh2: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: 2 } },
    dv2: { 1: { value: 0, direction: 'vertical', color: 'black', amount: 2 } },
    oh2: { 1: { value: 0, direction: 'horizontal', color: 'black', amount: -1 } },
    ov2: { 1: { value: 0, direction: 'vertical', color: 'black', amount: -1 } },
    hvb2: { 1: { value: 0, direction: 'vertical', color: 'blue', amount: 3 } },
    hvr2: { 1: { value: 0, direction: 'vertical', color: 'red', amount: 3 } },
    hvy2: { 1: { value: 0, direction: 'vertical', color: 'yellow', amount: 3 } },
    hdo2: { 1: { value: 0, direction: 'diagonal1', color: 'black', amount: 3 } },
    hdt2: { 1: { value: 0, direction: 'diagonal2', color: 'black', amount: 3 } }
}
let hard_deck = {...easy_deck, ...hard_cards};
let diff_deck = {...sum_deck, ...diff_cards};

let harder_deck = {...easy_deck, ...hard_cards, ...hard_cards2};

module.exports = { sum_deck, diff_deck, easy_deck, hard_deck, harder_deck, sprites}